[workspace]


resolver = "2"
members = ["task_1", "task_2/task_creator", "task_2/task_logger", "task_2/task_processor", "task_3", "task_4","task_5/task_service","task_5/task_executor","task_5/task_notifier"]
