version: '3.8'
services: 
  task_service: 
    container_name: task_service 
    build:
      context: ./task_service
      dockerfile: Dockerfile
    image: task_service
    ports:
        - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - L3.5


  task_executor: 
    container_name: task_executor
    build:
      context: ./task_executor
      dockerfile: Dockerfile
    image: task_service
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - L3.5   

  postgres:
    image: postgres:latest
    container_name: postgres
    mem_limit: 1024m
    healthcheck:
      test: bash -c '((echo >/dev/tcp/localhost/5432) &>/dev/null)'
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"  
    environment:
      - POSTGRES_PASSWORD=wb_tech
      - POSTGRES_USER=wb_tech
      - POSTGRES_DB=L3.5
    networks:
      - L3.5

  redis:
    image: docker.io/bitnami/redis:latest
    container_name: redis
    #ports:
    #  - 6379:6379
    environment:
      REDIS_PASSWORD: "wb_tech"
    healthcheck:
      test: ((echo >/dev/tcp/localhost/6379) &>/dev/null) || exit -1
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - L3.5

networks:
  L3.5:
    driver: bridge
    name: L3.5            