version: '2.1'
services: 
  panda:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: panda
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: nc -z localhost 8080 || exit 1
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TLS_ENABLED=false
      - KAFKA_SASL_ENABLED=false
  kafka:
    image: bitnami/kafka:3.6.1
    container_name: kafka
    healthcheck:
      test: ((echo >/dev/tcp/localhost/9092) &>/dev/null) || exit -1
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "9092:9092"  
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
