[app_config]
    [redis]
        host="redis"
        port=6379
        login="wb_tech"
        password="wb_tech"
        db=0
        max_connections=100
        wait=2
        create=1
    [last_notifier_tasks]
        path="./last_notifications.json"    
    [tracing]
        level_stdout="5"  #1-error,2-warn,3-info,4-debug,5-trace   
        level_otel="5"    #1-error,2-warn,3-info,4-debug,5-trace            
        url="http://grafana-tempo:4317"          